# Generated by Django 4.1.7 on 2023-04-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvisit',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='productvisit',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='productvisit',
            name='user',
        ),
    ]
