# Generated by Django 4.1.7 on 2023-04-30 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_productvisit_ip_address_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductVisit',
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
