# Generated by Django 4.1.7 on 2023-04-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_productvisit_product_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='original_price',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
